const countries = {
    "en-GB": "English",
    "kn-IN": "Kannada",
    "de-DE": "German",
    "dv-MV": "Maldivian",
    "es-ES": "Spanish",
    "fr-FR": "French",
    "gu-IN": "Gujarati",
    "he-IL": "Hebrew",
    "hi-IN": "Hindi",
    "it-IT": "Italian",
    "ja-JP": "Japanese",
    "ko-KR": "Korean",
    "ms-MY": "Malay",
    "ne-NP": "Nepali",
    "pa-IN": "Panjabi",
    "pt-PT": "Portuguese",
    "ru-RU": "Russian",
    "sv-SE": "Swedish",
    "ta-LK": "Tamil",
    "te-IN": "Telugu",
    "th-TH": "Thai",
    "tr-TR": "Turkish",
    "uk-UA": "Ukrainian",
    "vi-VN": "Vietnamese",
    "zu-ZA": "Zulu"
}